Erpnext/urls.py
from django.conf.urls import url
from Erpnext.views import *
from . import views

urlpatterns = [
	url(r'^register$', RegistrationView.as_view(), name = 'register'),
	url(r'^login$', LoginView.as_view(), name = 'login'),

]

two/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
     url(r'^Erpnext/', include('Erpnext.urls', namespace='Erpnext')),

    # url(r'^admin/', admin.site.urls),
]

Erpnext/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class person(models.Model):
	fname = models.CharField(max_length=20, null=True, blank = True)
	lname = models.CharField(max_length=20, null=True, blank = True)
	email = models.CharField(max_length=30 , null = True, blank = True)
	# username = models.CharField(max_length=20, null=True, blank = True)

	def __str__(self):
		return str(self.fname) + " " + str(self.lname)

Erpnext/forms.py
from django.forms import ModelForm
from Erpnext.models import person

class AddUserForm(ModelForm):
	class Meta:
		model = person
		fields = ['fname', 'lname', 'email']

Erpnext/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View, DetailView
from Erpnext.models import person
from django.template import Context
from django.views.generic import TemplateView
import forms
#
# def index(request):
# 	return render(request, 'main.html')

class LoginView(View):

	def get(self, request):
		return render(self.request, 'login.html')

	def post(self, request):
		user = User()
		username = request.POST.get('username')
		password = request.POST.get('password')
		user = authenticate(username = username, password =password)
		if user is not None:
		    # the password verified for the user
		  		login(request, user)
				print("LOGIN SUCCESS")
				return render(self.request, 'register.html')

		else:
			print("Error")
			return render(self.request, 'login.html')





class RegistrationView(View):

	def get(self, request):
		return render(self.request, 'register.html')

	def post(self, request):
		Human = person()
		# personInfo = SchoolInfo()

		Human.fname = request.POST['fname']
		Human.lname = request.POST['lname']
		Human.email = request.POST['email']
		Human.save()

		user = User.objects.create_user(request.POST['username'], Human.email, request.POST['password'])

		user.last_name = Human.lname
		user.first_name = Human.fname
		user.save()
		# print(user.username)

		# return render(self.request, 'login.html')
		return render(self.request, 'register.html')

Erpnext/templates/login.html
<!DOCTYPE html>
<html>
<head>
	<title>Log In to Site</title>
</head>
<body>

	<h1>Log In</h1>
	<br>
	<form  action="{% url 'Erpnext:login' %}" method="POST" id="loginForm">
	    {% csrf_token %}
		Username:  <input type="text" name="username"><br><br>
    Password: <input type="text" name="password"><br><br>
		<input type="submit" name="login" value="Log In">

	</form>
</body>
</html>

Erpnext/templates/register.html
<!DOCTYPE html>
<html>
<head>
	<title>Register Account</title>
</head>
<body>

	<h1>Registration Form</h1>
	<br>
	<form  action="{% url 'Erpnext:register' %}" method="POST" id="registerForm">
	    {% csrf_token %}
		First name:  <input type="text" name="fname"><br><br>
		Last name: <input type="text" name="lname"><br><br>
	  Email Address: <input type="text" name="email"><br><br>
		Username: <input type="text" name="username"><br><br>
		Password: <input type="text" name="password"><br><br>
		<input type="submit" name="register" value="Register">

	</form>
</body>
</html>